title: Hardware Hacking Brasil
email: hhbrasil@no-valid-email
description: Comunidade - Hardware Hacking Brasil
baseurl: "/"
url: "https://hardwarehacking.com.br"

# Build settings
theme: jekyll-theme-console
style: hacker

markdown:       kramdown
include:
  - _pages

sass:
  sass_dir:     _sass
  style:        compressed

plugins_dir: ./_plugins

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-spaceship

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

data:
  en:
    months:
      - January
      - February
      - March
      - April
      - May
      - June
      - July
      - August
      - September
      - October
      - November
      - December
  pt:
    months:
      - Janeiro
      - Fevereiro
      - Março
      - Abril
      - Maio
      - Junho
      - Julho
      - Agosto
      - Setembro
      - Outubro
      - Novembro
      - Dezembro

# Where things are
jekyll-spaceship:
  # default enabled process
  processors:
    - table-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor

  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'outline: none;'
      allow: 'encrypted-media; picture-in-picture'

  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/